const fonts = {
    black: 'Montserrat-Black',
    BlackItalic: 'Montserrat-BlackItalic',
    bold: 'Montserrat-Bold',
    boldItalic: 'Montserrat-BoldItalic',
    ExtraBold: 'Montserrat-ExtraBold',
    ExtraBoldItalic: 'Montserrat-ExtraBoldItalic',
    ExtraLight: 'Montserrat-ExtraLight',
    ExtraLightItalic: 'Montserrat-ExtraLightItalic',
    Italic: 'Montserrat-Italic',
    Light: 'Montserrat-Light',
    LightItalic: 'Montserrat-LightItalic',
    medium: 'Montserrat-Medium',
    MediumItalic: 'Montserrat-MediumItalic',
    regular: 'Montserrat-Regular',
    semiBold: 'Montserrat-SemiBold',
    SemiBoldItalic: 'Montserrat-SemiBoldItalic',
    Thin: 'Montserrat-Thin',
    ThinItalic: 'Montserrat-ThinItalic',

    poppins_regular: 'Poppins-Regular',
    poppins_semiBold: 'Poppins-SemiBold',
    poppins_bold: 'Poppins-Bold',
    poppins_medium: 'Poppins-Medium',
    poppins_black:'Poppins-Black',
    poppins_BlackItalic:'Poppins-BlackItalic',
    poppins_boldItalic:'Poppins-BoldItalic',
    poppins_ExtraBold:'Poppins-ExtraBold',
    poppins_ExtraBoldItalic:'Poppins-ExtraBoldItalic',
    poppins_ExtraLight:'Poppins-ExtraLight',
    poppins_ExtraLightItalic:'Poppins-ExtraLightItalic',
    poppins_Italic:'Poppins-Italic',
    poppins_Light:'Poppins-Light',
    poppins_LightItalic:'Poppins-LightItalic',
    poppins_MediumItalic:'Poppins-MediumItalic',
    poppins_SemiBoldItalic:'Poppins-SemiBoldItalic',
    poppins_Thin:'Poppins-Thin',
    poppins_ThinItalic:'Poppins-ThinItalic',
};

export default fonts;
